title: Chris Tran
logo: "/images/picture.png?raw=true"
description: >
  I am currently pursing a Master's degree in Business Analytics, Data Science at Simon Business School, University of Rochester.
  <br><br>
  I am looking for a job opportunity where I will join a team to utilize advanced analytics and machine learning techniques to build models capable of leveraging all data that business generates and develop solutions that help deliver significant value to the organization.
  <br><br>
  <a href="https://www.linkedin.com/in/chriskhanhtran/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
